# Generated by Django 5.0.3 on 2024-03-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.DateTimeField(blank=True, null=True)),
                ('code', models.TextField()),
                ('memory_usage', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
