# Generated by Django 5.0.3 on 2024-03-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onecode',
            name='pref_language',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
