# Generated by Django 5.0.3 on 2024-04-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_onecode_pref_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savelink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('pref_language', models.CharField(max_length=255, null=True)),
                ('unique_link', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
