# Generated by Django 5.0.3 on 2024-06-14 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_userprofile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersolvedquestionlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usersolvedquestionlist",
                to="api.userprofile",
            ),
        ),
    ]
