# Generated by Django 5.0.3 on 2024-04-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_savelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savelink',
            name='unique_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
