# Generated by Django 5.0.3 on 2024-04-23 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_savelink_unique_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=225)),
                ('slug', models.SlugField(max_length=225)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Input', models.CharField(max_length=225)),
                ('Output', models.CharField(max_length=225)),
                ('Explanation', models.CharField(max_length=255)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exaples', to='api.problem')),
            ],
        ),
    ]
