# Generated by Django 5.0.3 on 2024-06-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_userprofile_picture_userprofile_picture_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="picture_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
