# Generated by Django 5.0.3 on 2024-04-23 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_problem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='api.problem'),
        ),
    ]
